import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';

import { Navbar } from '@/components/Navbar';
import './globals.css';
import Image from 'next/image';

import { Footer } from '@/components/Footer';
import { ThemeProvider, ThemeToggle } from '@/components/ThemeProvider';

const robotoSans = Roboto({
	variable: '--font-roboto-sans',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang='en' suppressHydrationWarning>
  <body className={`${robotoSans.variable} font-sans antialiased bg-background`}>
		<ThemeProvider>
    
    <header className='fixed z-60 w-full h-22 backdrop-blur-md md:h-18 md:px-20 mx-auto md:w-full'>
      <div className='flex flex-row items-start justify-between w-full h-22 px-4 py-6 md:max-w-7xl md:h-18 md:pt-5 md:pb-5 md:px-24 mx-auto'>
        
        {/* Left box - Logo hoặc khoảng trống */}
        <div className='hidden md:block md:w-12 md:h-10'>
          {/* Bạn có thể đặt Logo ở đây */}
        </div>

				<div className='w-10 h-10 md:hidden'></div>

        {/* Navigation bar - Căn giữa */}
        <nav className='flex md:items-center md:justify-center md:overflow-hidden'>
          <Navbar />
        </nav>

        {/* Light button - Cố định hoặc nằm trong Flex */}
      
          <div className='flex items-center justify-center h-10 w-12 rounded-full bg-foreground shadow-lg hover:scale-110 transition-transform'>
            <ThemeToggle />
          </div>
      </div>
    </header>

    {/* Main Content */}
    <main className='pt-22 md:pt-12 flex flex-col items-center w-full'>
      <div className='w-full max-w-7xl px-4 pt-0 md:pt-6 pb-16 md:px-20 mx-auto'>
        {children}
      </div>
    </main>

    {/* Footer phải nằm TRONG body */}
    <div className='w-full max-w-7xl px-4 md:px-20 mx-auto'><Footer /></div>
		</ThemeProvider>
  </body>
</html>
	);
}
